title: Centrarium
subtitle: "A simple yet classy theme for your Jekyll website or blog"
email: "tnwls9712@naver.com"
name: Hwang Su jin
theme: jekyll-theme-slate
logo: "https://github.com/sujin16/sujin16.github.io/issues/1#issue-786919779"
